version: '3.8'

services:
  cloudflare-dns:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-super-secret-key-change-this
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
      - ./dns_manager.db:/app/dns_manager.db
    restart: unless-stopped

volumes:
  dns_data: 