version: '3.8'

services:
  cloudflare-dns:
    image: antalkon/cloudflare-dns-manager:latest
    container_name: cloudflare-dns-manager
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - dns_data:/app/instance
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-ru}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-false}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dns_data:
    driver: local

# Использование:
# wget https://raw.githubusercontent.com/antalkon/cloudflare-dns-manager/main/docker-compose.standalone.yml -O docker-compose.yml
# docker-compose up -d 